### ISSUE TITLE
Composer Install Problem

### ISSUE THREAD

**Issue by kalkulatorcetak** [abydahana/Aksara4#2]
Problem 1
    - Installation request for laminas/laminas-escaper 2.7.0 -> satisfiable by laminas/laminas-escaper[2.7.0].
    - laminas/laminas-escaper 2.7.0 requires php ^7.3 || ~8.0.0 -> your PHP version (7.2.24) does not satisfy that requirement.
  Problem 2
    - laminas/laminas-escaper 2.7.0 requires php ^7.3 || ~8.0.0 -> your PHP version (7.2.24) does not satisfy that requirement.
    - codeigniter4/framework v4.0.4 requires laminas/laminas-escaper ^2.6 -> satisfiable by laminas/laminas-escaper[2.7.0].
    - Installation request for codeigniter4/framework v4.0.4 -> satisfiable by codeigniter4/framework[v4.0.4].

**Comment by abydahana** [comment]
Hello there, thank you for submitting your issue! This is the first issue submitted by user that we waiting for.

About the problem of installing the dependencies through `composer` is caused by the `lock` file that refer to our debuging device. We should write `composer update` instead of `composer install` because the `install` command will refer to the existing parameter on the `composer.lock` file.

Please run `composer update` instead.

We also remove some dependencies below due it's not required anymore with our pre-installed modules:
1. FTP Client;
2. PayPal Client API.

In case you don't want to correcting the missing dependencies above one by one, please re-download the newest Aksara4 repository and try again.

Thank you...
